import type { Metadata } from "next";
import { Geist } from "next/font/google"; // Import from Google
import NavBar from "../components/NavBar";
import "./globals.css";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans", // This connects it to Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geistSans.className}>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
